### ISSUE TITLE
TreeView Control

### ISSUE THREAD

**Issue by ghost1372** [onein528/RegistryValley#6]
Hi, Tnx for Great app.
can you make treeview control as a standalone library so we can use it in our app? currently this is a little confusing.
searching nodes in built-in treeview is a little hard so i am looking for using your custom treeview which is based on listview.

**Comment by 0x5bfa** [comment]
Nope, I don't have time.

But as a implementation note, I made an UserControl for it, which is almost standalone.
https://github.com/0x5bfa/FluentRegEdit/blob/main/src/RegistryValley.App/UserControls/TreeView.xaml
And it has my own control that displays tree branch borders called [BranchDisplay](https://github.com/0x5bfa/FluentRegEdit/blob/main/src/RegistryValley.App/UserControls/BranchDisplay.xaml)

1. Create flat collection instead of tree collection and set depth in each item
2. Set it to the control



This easy.
